---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r}
require(ggplot2);
require(scales);

setwd("C:\\Coursera\\assignment");
activitydata <- read.csv("activity.csv");
activitydata$date = as.Date(activitydata$date, format="%Y-%M-%d")
```

## What is mean total number of steps taken per day?

```{r}
totalstepsperday <- aggregate(steps ~ date, data=activitydata, FUN=sum);

meansteps = mean(totalstepsperday$steps);
mediansteps = median(totalstepsperday$steps);

ggplot(totalstepsperday, aes(x=date, y=steps)) +
    xlab("Date") + ylab("Total Steps") + 
    geom_bar(stat="identity") +
    scale_x_date(labels = date_format("%m-%d-%Y")) +
    ggtitle("Total Steps by Date") +
    theme(plot.title = element_text(lineheight=.8, face="bold"));

```

Mean total steps per day = `r meansteps`

Median total steps per day = `r strmediansteps`

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?

